Fix the error that company repressentative cannot be approved when the status in csv is null:
1.it seems to be line 26 in CompanyRepresentativeSerializer.java, when reading null it's actually reading string "null" instead of null value, so Boolean.valueOf("null") returns false
2.java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "models.CompanyRepresentative.isApproved()" is null at controllers.UserManager.getRespectiveUserList(UserManager.java:179)
at controllers.UserManager.<init>(UserManager.java:57)
at Main.main(Main.java:32)
Line 179 has if(cr.isApproved() == true) which tries to unbox a null Boolean. When the status is null (pending approval), this causes a NullPointerException